### PR TITLE
Launch script for IDE

### PR DESCRIPTION
**Pull request by seletz**
Added launch script for IDE debugging and launching.

Signed-off-by: Stefan Eletzhofer <se@nexiles.de>

### CODE REVIEW

**Comment by mherrmann** [comment]
Thank you. You can simply run `src/main/python/tutorial/main.py`, provided the PYTHONPATH and Interpreter are set up correctly:

image

image

This way, the `launcher.py` is not required. Does that also let you do what you want?

**Comment by mherrmann** [comment]
image

**Comment by seletz** [comment]
Hi, thanks -- I think I have tried that but it broke while debugging.  I'll check!

**Comment by mherrmann** [comment]
Thanks. Do let me know!

**Comment by mherrmann** [comment]
I added explanations on how fbs apps can be run from IDEs (or other environments) to the README [here](https://github.com/mherrmann/fbs-tutorial#using-an-ide).

**Comment by mherrmann** [comment]
Closing this PR because I think it's now explained well in the README :-)

**Pull request closed without merging**
